/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _APPLICATION_H_RPCGEN
#define _APPLICATION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Request_Auth {
	char *clientId;
	int autoRefresh;
};
typedef struct Request_Auth Request_Auth;

struct Response_Auth {
	char *token;
	char *status;
};
typedef struct Response_Auth Response_Auth;

struct Request_Approve {
	char *authToken;
};
typedef struct Request_Approve Request_Approve;

struct Response_Approve {
	int isSigned;
};
typedef struct Response_Approve Response_Approve;

struct Request_Bearer {
	char *authToken;
	int isSigned;
};
typedef struct Request_Bearer Request_Bearer;

struct Response_Bearer {
	char *accessToken;
	char *refreshToken;
	char *status;
	int timeout;
};
typedef struct Response_Bearer Response_Bearer;

struct Renew_Request_Bearer {
	char *refreshToken;
};
typedef struct Renew_Request_Bearer Renew_Request_Bearer;

struct Renew_Response_Bearer {
	char *newAccessToken;
	char *newRefreshToken;
	int timeout;
};
typedef struct Renew_Response_Bearer Renew_Response_Bearer;

struct Request_Validate_Action {
	char *action;
	char *resource;
	char *accessToken;
};
typedef struct Request_Validate_Action Request_Validate_Action;

struct Response_Validate_Action {
	char *status;
};
typedef struct Response_Validate_Action Response_Validate_Action;

#define MANAGER_OF_RESOURCES_APP 0x12345678
#define MANAGER_OF_RESOURCES_APP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define AUTHENTICATE 1
extern  Response_Auth * authenticate_1(Request_Auth *, CLIENT *);
extern  Response_Auth * authenticate_1_svc(Request_Auth *, struct svc_req *);
#define APPROVE 2
extern  Response_Approve * approve_1(Request_Approve *, CLIENT *);
extern  Response_Approve * approve_1_svc(Request_Approve *, struct svc_req *);
#define BEARER 3
extern  Response_Bearer * bearer_1(Request_Bearer *, CLIENT *);
extern  Response_Bearer * bearer_1_svc(Request_Bearer *, struct svc_req *);
#define RENEW_BEARER 4
extern  Renew_Response_Bearer * renew_bearer_1(Renew_Request_Bearer *, CLIENT *);
extern  Renew_Response_Bearer * renew_bearer_1_svc(Renew_Request_Bearer *, struct svc_req *);
#define VALIDATE_ACTION 5
extern  Response_Validate_Action * validate_action_1(Request_Validate_Action *, CLIENT *);
extern  Response_Validate_Action * validate_action_1_svc(Request_Validate_Action *, struct svc_req *);
extern int manager_of_resources_app_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AUTHENTICATE 1
extern  Response_Auth * authenticate_1();
extern  Response_Auth * authenticate_1_svc();
#define APPROVE 2
extern  Response_Approve * approve_1();
extern  Response_Approve * approve_1_svc();
#define BEARER 3
extern  Response_Bearer * bearer_1();
extern  Response_Bearer * bearer_1_svc();
#define RENEW_BEARER 4
extern  Renew_Response_Bearer * renew_bearer_1();
extern  Renew_Response_Bearer * renew_bearer_1_svc();
#define VALIDATE_ACTION 5
extern  Response_Validate_Action * validate_action_1();
extern  Response_Validate_Action * validate_action_1_svc();
extern int manager_of_resources_app_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Request_Auth (XDR *, Request_Auth*);
extern  bool_t xdr_Response_Auth (XDR *, Response_Auth*);
extern  bool_t xdr_Request_Approve (XDR *, Request_Approve*);
extern  bool_t xdr_Response_Approve (XDR *, Response_Approve*);
extern  bool_t xdr_Request_Bearer (XDR *, Request_Bearer*);
extern  bool_t xdr_Response_Bearer (XDR *, Response_Bearer*);
extern  bool_t xdr_Renew_Request_Bearer (XDR *, Renew_Request_Bearer*);
extern  bool_t xdr_Renew_Response_Bearer (XDR *, Renew_Response_Bearer*);
extern  bool_t xdr_Request_Validate_Action (XDR *, Request_Validate_Action*);
extern  bool_t xdr_Response_Validate_Action (XDR *, Response_Validate_Action*);

#else /* K&R C */
extern bool_t xdr_Request_Auth ();
extern bool_t xdr_Response_Auth ();
extern bool_t xdr_Request_Approve ();
extern bool_t xdr_Response_Approve ();
extern bool_t xdr_Request_Bearer ();
extern bool_t xdr_Response_Bearer ();
extern bool_t xdr_Renew_Request_Bearer ();
extern bool_t xdr_Renew_Response_Bearer ();
extern bool_t xdr_Request_Validate_Action ();
extern bool_t xdr_Response_Validate_Action ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_APPLICATION_H_RPCGEN */
