/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "application.h"

bool_t
xdr_Request_Auth (XDR *xdrs, Request_Auth *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->clientId, 20))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->autoRefresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response_Auth (XDR *xdrs, Response_Auth *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->status, 50))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Request_Approve (XDR *xdrs, Request_Approve *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->authToken, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response_Approve (XDR *xdrs, Response_Approve *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->isSigned))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Request_Bearer (XDR *xdrs, Request_Bearer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->authToken, 20))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->isSigned))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response_Bearer (XDR *xdrs, Response_Bearer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->accessToken, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refreshToken, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->status, 50))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Renew_Request_Bearer (XDR *xdrs, Renew_Request_Bearer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->refreshToken, 20))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Renew_Response_Bearer (XDR *xdrs, Renew_Response_Bearer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->newAccessToken, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->newRefreshToken, 20))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Request_Validate_Action (XDR *xdrs, Request_Validate_Action *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->action, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, 20))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->accessToken, 30))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Response_Validate_Action (XDR *xdrs, Response_Validate_Action *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->status, 50))
		 return FALSE;
	return TRUE;
}
