/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "application.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "headers/inputReader.h"
#include "headers/userData.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

char** userList;
char** resourceList;
PermissionsQueue* permissionsQueue;
int numberOfOperations;
UserInfoList* userInfoDB;

static void
manager_of_resources_app_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Request_Auth authenticate_1_arg;
		Request_Approve approve_1_arg;
		Request_Bearer bearer_1_arg;
		Renew_Request_Bearer renew_bearer_1_arg;
		Request_Validate_Action validate_action_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case AUTHENTICATE:
		_xdr_argument = (xdrproc_t) xdr_Request_Auth;
		_xdr_result = (xdrproc_t) xdr_Response_Auth;
		local = (char *(*)(char *, struct svc_req *)) authenticate_1_svc;
		break;

	case APPROVE:
		_xdr_argument = (xdrproc_t) xdr_Request_Approve;
		_xdr_result = (xdrproc_t) xdr_Response_Approve;
		local = (char *(*)(char *, struct svc_req *)) approve_1_svc;
		break;

	case BEARER:
		_xdr_argument = (xdrproc_t) xdr_Request_Bearer;
		_xdr_result = (xdrproc_t) xdr_Response_Bearer;
		local = (char *(*)(char *, struct svc_req *)) bearer_1_svc;
		break;

	case RENEW_BEARER:
		_xdr_argument = (xdrproc_t) xdr_Renew_Request_Bearer;
		_xdr_result = (xdrproc_t) xdr_Renew_Response_Bearer;
		local = (char *(*)(char *, struct svc_req *)) renew_bearer_1_svc;
		break;

	case VALIDATE_ACTION:
		_xdr_argument = (xdrproc_t) xdr_Request_Validate_Action;
		_xdr_result = (xdrproc_t) xdr_Response_Validate_Action;
		local = (char *(*)(char *, struct svc_req *)) validate_action_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	//Initialize user list, resource list, permissions queue and the database
	userList = readUserList(argv[1]);
	resourceList = readResourceList(argv[2]);
	permissionsQueue = readPermissionsQueue(argv[3]);
	numberOfOperations = atoi(argv[4]);
	userInfoDB =  initializeList(&userInfoDB);

	// Does not allow buffering for printing
	setvbuf(stdout, 0, _IONBF, 0);

	pmap_unset (MANAGER_OF_RESOURCES_APP, MANAGER_OF_RESOURCES_APP_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MANAGER_OF_RESOURCES_APP, MANAGER_OF_RESOURCES_APP_VERSION, manager_of_resources_app_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MANAGER_OF_RESOURCES_APP, MANAGER_OF_RESOURCES_APP_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MANAGER_OF_RESOURCES_APP, MANAGER_OF_RESOURCES_APP_VERSION, manager_of_resources_app_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MANAGER_OF_RESOURCES_APP, MANAGER_OF_RESOURCES_APP_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
